#!/bin/bash

installuv() {
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        curl -LsSf https://astral.sh/uv/install.sh | sh
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        brew install uv
    else
        echo "Unsupported operating system."
    fi
}

id() {
    . .venv/bin/activate
    VERSION=$(python -m api.version)
    APP_NAME=$(python -m api.app_name)
    echo "$APP_NAME $VERSION"
}

setup() {
    uv venv
    source .venv/bin/activate
    uv pip install -r dev-requirements.txt
    pre-commit install
}

devcompile() {
    uv pip compile requirements.in > requirements.txt
    uv pip compile requirements.in dev-requirements.in > dev-requirements.txt
}

devsync() {
    source .venv/bin/activate
    uv pip sync requirements.txt
    uv pip sync dev-requirements.txt
}

lint() {
    source .venv/bin/activate
    ruff check .
    ruff format .
    mypy .
    bandit -r api
}

test() {
    source .venv/bin/activate
    python -m pytest -s --cov=api/ --cov=tests --cov-report=term-missing --cov-report html "${@:2}"
}

pre_commit() {
    source .venv/bin/activate
    pre-commit run --all-files
}

wrap() {
    . .venv/bin/activate
    "${@:2}"
}

serve() {
    . .venv/bin/activate
    IS_DEV=true uvicorn api.app:app --reload --log-level debug --port 17581
}

build_image() {
    set -eux
    . .venv/bin/activate
    VERSION=$(python -m api.version)
    APP_NAME=$(python -m api.app_name)
    docker build -t nillebco/$APP_NAME:$VERSION .
    if [ -f $APP_NAME.tar.gz ]; then
        rm $APP_NAME.tar.gz
    fi
    docker save nillebco/$APP_NAME:$VERSION > $APP_NAME.tar
    gzip $APP_NAME.tar
    sha256sum $APP_NAME.gz
}

zapscan() {
    mkdir data
    docker run -v $(pwd)/data:/zap/wrk:rw -t owasp/zap2docker-stable zap-api-scan.py -t http://host.docker.internal:17581/openapi.json -f openapi -r api-scan.html
}

case "$1" in
    installuv)
        installuv
        ;;
    id)
        id
        ;;
    setup)
        setup
        ;;
    devcompile)
        devcompile
        ;;
    devsync)
        devsync
        ;;
    lint)
        lint
        ;;
    test)
        test $@
        ;;
    pre-commit)
        pre_commit
        ;;
    wrap)
        wrap $@
        ;;
    build-image)
        build_image
        ;;
    zapscan)
        zapscan
        ;;
    serve)
        serve
        ;;
    *)
        echo "Error: Invalid command. Available commands: setup | devcompile | devsync | serve"
        ;;
esac
